
/* AUTOGENERATED DO NOT MODIFY */

/**
 ******************************************************************************
 * @file    stai_network.h
 * @author  SRA Artificial Intelligence & Embedded Architectures
 * @brief   Implementation of ST.AI platform public APIs for ATON
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef __STAI_ATON_NETWORK_H
#define __STAI_ATON_NETWORK_H

// Include ATON runtime/library configuration file
#include "ll_aton_config.h"
#include "ll_aton_stai_internal.h"

// clang-format off
#ifdef __cplusplus
extern "C"
{
#endif

/*
 * NOTE: the beyond macro MUST be set to the same value when compiling the different ATON runtime/library, and
 *       AtoNN compiler generated files
 */
#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

// Derive alignment
#define _alignof(t)                                                                                                    \
  ((sizeof(t) > 1) ? offsetof(                                                                                         \
                         struct {                                                                                      \
                           char c;                                                                                     \
                           t x;                                                                                        \
                         },                                                                                            \
                         x)                                                                                            \
                   : 1)

// Include ST.AI headers
#include "stai_aton_common.h"

/*****************************************************************************/
#define STAI_NETWORK_CONTEXT_SIZE      ((stai_size)sizeof(_stai_aton_context))
#define STAI_NETWORK_CONTEXT_ALIGNMENT (_alignof(_stai_aton_context))

/*****************************************************************************/
STAI_API_DECLARE_BEGIN

/*****************************************************************************/
/* ST.AI API extensions are available */
#ifndef HAS_STAI_EXT
#define HAS_STAI_EXT
#endif // HAS_STAI_EXT

/*****************************************************************************/
/*  Network management APIs  */
STAI_API_ENTRY
stai_return_code stai_network_init(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_network_deinit(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_network_run(stai_network *network, const stai_run_mode mode);

STAI_API_ENTRY
stai_return_code stai_network_train(stai_network *network, const stai_run_mode mode);

/*****************************************************************************/
/*  Getters APIs  */

// needed only for python bindings to query internal context byte size
STAI_API_ENTRY
static inline stai_size stai_network_get_context_size(void)
{
  return STAI_NETWORK_CONTEXT_SIZE;
}

STAI_API_ENTRY
stai_return_code stai_network_get_info(stai_network *network, stai_network_info *info);

STAI_API_ENTRY
stai_return_code stai_network_get_inputs(stai_network *network, stai_ptr *inputs, stai_size *n_inputs);

STAI_API_ENTRY
stai_return_code stai_network_get_weights(stai_network *network, stai_ptr *weights, stai_size *n_weights);

STAI_API_ENTRY
stai_return_code stai_network_get_outputs(stai_network *network, stai_ptr *outputs, stai_size *n_outputs);

STAI_API_ENTRY
stai_return_code stai_network_get_activations(stai_network *network, stai_ptr *activations,
                                                            stai_size *n_activations);

STAI_API_ENTRY
stai_return_code stai_network_get_states(stai_network *network, stai_ptr *states, stai_size *n_states);
STAI_API_ENTRY
stai_return_code stai_network_get_error(stai_network *network);

/*****************************************************************************/
/*  Setters APIs  */

/**
 * @brief Set array of input buffers
 * @param network NN for which to set the input buffers
 * @param inputs array of input buffer pointers
 * @param n_inputs number of elements in the input buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_network_set_inputs(stai_network *network, const stai_ptr *inputs,
                                                       const stai_size n_inputs);

/**
 * @brief Set array of weight buffers
 * @param network NN for which to set the weight buffers
 * @param weights array of weight buffer pointers
 * @param n_weights number of elements in the weight buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for weights
 */
STAI_API_ENTRY
stai_return_code stai_network_set_weights(stai_network *network, const stai_ptr *weights,
                                                        const stai_size n_weights);

/**
 * @brief Set array of output buffers
 * @param network NN for which to set the output buffers
 * @param outputs array of output buffer pointers
 * @param n_outputs number of elements in the output buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_network_set_outputs(stai_network *network, const stai_ptr *outputs,
                                                        const stai_size n_outputs);

/**
 * @brief Set array of activation buffers
 * @param network NN for which to set the activation buffers
 * @param activations array of activation buffer pointers
 * @param n_activations number of elements in the activation buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for activations
 */
STAI_API_ENTRY
stai_return_code stai_network_set_activations(stai_network *network, const stai_ptr *activations,
                                                            const stai_size n_activations);

STAI_API_ENTRY
stai_return_code stai_network_set_states(stai_network *network, const stai_ptr *states,
                                                       const stai_size n_states);

STAI_API_ENTRY
stai_return_code stai_network_set_callback(stai_network *network, const stai_event_cb cb,
                                                         void *cb_cookie);

/***************************************************************************/
/*  Extended ATON Target Specific APIs  */

/** Asynchronous Execution **/
/**
 * @brief Continue network execution of an asynchronously started/run network
 *        (i.e. network was started/run in `stai_run_mode::STAI_MODE_ASYNC` mode)
 * @details Running a network in asynchronous mode (see function `stai_network_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_network_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_network_run()` again until the network's execution has
 *          actually finished.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_network_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_network_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_network_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_network_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_network_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_network_run_continue()`
 * again)
 * @param[in] network network opaque pointer
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_network_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_run_continue(stai_network *network);

/**
 * @brief Get execution status of a network
 * @details Running a network in asynchronous mode (see function `stai_network_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_network_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_network_run()` again until the network's execution has
 *          actually finish.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_network_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_network_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_network_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_network_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_network_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_network_run_continue()`
 * again)
 * @param[in] network network handle
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_network_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_get_nn_run_status(stai_network *network);

/**
 * @brief Prepare the network for a new inference
 * @details In case `stai_ext_network_get_nn_run_status()` returns either `STAI_DONE` or
 *          `STAI_RUNNING_NO_WFE` (when called by the thread which actually executes the inference of the passed
 *          `network`), prepare `network` for another/new inference run.
 * @param[in] network network handle
 * @return
 *
 * @note May only be called by the thread actually executing the inference of `network`!
 * @note Necessary only in case current inference is/has been executed asynchronously!
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_new_inference(stai_network *network);

/*****************************************************************************/
STAI_API_DECLARE_END

/*****************************************************************************/
#define STAI_NETWORK_STATES_NUM  (0)
#define STAI_NETWORK_STATES_SIZE (0)

/*****************************************************************************/
/************************** SUBSTITUTABLE section ****************************/
/*****************************************************************************/

/**************************** Cache line size(s) *****************************/
#ifndef STAI_CACHE_MCU_LINESIZE
#define STAI_CACHE_MCU_LINESIZE (32)
#elif (STAI_CACHE_MCU_LINESIZE != 32)
#error "MCU cache line size mismatch"
#endif

/* NPU cache extension is available */
#ifndef STAI_EXT_CACHE_HAS_NPU
#define STAI_EXT_CACHE_HAS_NPU
#endif
#define STAI_NETWORK_EXT_CACHE_HAS_NPU

#ifndef STAI_EXT_CACHE_NPU_LINESIZE
#define STAI_EXT_CACHE_NPU_LINESIZE (64)
#elif (STAI_EXT_CACHE_NPU_LINESIZE != 64)
#error "NPU cache line size mismatch"
#endif

#ifndef STAI_CACHE_USER_BUFFER_ALIGNMENT
#define STAI_CACHE_USER_BUFFER_ALIGNMENT STAI_CACHE_MCU_LINESIZE  // NOTE: user allocated buffers are assumed not to be NPU cacheable!
#endif

/********************************** INPUTS ***********************************/
#define STAI_NETWORK_IN_NUM (1)
#define STAI_NETWORK_IN_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_NETWORK_IN_NAMES \
  { \
    "Input_0_out_0" \
  }
#define STAI_NETWORK_IN_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_NETWORK_IN_SIZES \
  { \
    2048 \
  }
#define STAI_NETWORK_IN_SIZES_BYTES \
  { \
    2048 \
  }

#define STAI_NETWORK_IN_1_ALIGNMENT (32)
#define STAI_NETWORK_IN_1_NAME "Input_0_out_0"
#define STAI_NETWORK_IN_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_FIRST)
#define STAI_NETWORK_IN_1_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_IN_1_SIZE (2048)
#define STAI_NETWORK_IN_1_SIZE_BYTES (2048)
#define STAI_NETWORK_IN_1_CHANNEL (1)
#define STAI_NETWORK_IN_1_HEIGHT (32)
#define STAI_NETWORK_IN_1_WIDTH (64)
#define STAI_NETWORK_IN_1_BATCH (1)
#define STAI_NETWORK_IN_1_RANK (4)
#define STAI_NETWORK_IN_1_SHAPE \
  { \
    1, 32, 64, 1 \
  }
#define STAI_NETWORK_IN_1_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_IN_1_SCALES \
  { \
    0.00392156885936856 \
  }
#define STAI_NETWORK_IN_1_OFFSETS \
  { \
    -128 \
  }

/********************************** OUTPUTS **********************************/
#define STAI_NETWORK_OUT_NUM (1)
#define STAI_NETWORK_OUT_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_NETWORK_OUT_NAMES \
  { \
    "Quantize_19_out_0" \
  }
#define STAI_NETWORK_OUT_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_NETWORK_OUT_SIZES \
  { \
    6 \
  }
#define STAI_NETWORK_OUT_SIZES_BYTES \
  { \
    6 \
  }

#define STAI_NETWORK_OUT_1_ALIGNMENT (32)
#define STAI_NETWORK_OUT_1_NAME "Quantize_19_out_0"
#define STAI_NETWORK_OUT_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE)
#define STAI_NETWORK_OUT_1_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_OUT_1_SIZE (6)
#define STAI_NETWORK_OUT_1_SIZE_BYTES (6)
#define STAI_NETWORK_OUT_1_CHANNEL (1)
#define STAI_NETWORK_OUT_1_HEIGHT (1)
#define STAI_NETWORK_OUT_1_WIDTH (6)
#define STAI_NETWORK_OUT_1_RANK (2)
#define STAI_NETWORK_OUT_1_SHAPE \
  { \
    1, 6 \
  }
#define STAI_NETWORK_OUT_1_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_OUT_1_SCALES \
  { \
    0.00175729754846543 \
  }
#define STAI_NETWORK_OUT_1_OFFSETS \
  { \
    -24 \
  }

/********************************** WEIGHTS **********************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_NETWORK_WEIGHTS_NUM (16)
#define STAI_NETWORK_WEIGHTS_ALIGNMENTS \
  { \
    32, 32, 32, 32, 16, 16, 32, 16, 16, 16, 32, 16, 32, 16, 16, 32 \
  }
#define STAI_NETWORK_WEIGHTS_NAMES \
  { \
    "Conv2D_4_weights", "Conv2D_8_weights", "Conv2D_13_weights", "Gemm_18_weights_transposed_3", "Conv2D_4_zero_off_8", "Conv2D_4_off_bias_14", "Conv2D_8_zero_off_17", "Conv2D_8_off_bias_23", "Conv2D_13_zero_off_26", "Conv2D_13_off_bias_32", "Gemm_18_conv_4_zero_off_35", "Gemm_18_conv_4_off_bias_41", "Conv2D_4_off_bias_12_A_16_108", "Conv2D_8_off_bias_21_A_16_110", "Conv2D_13_off_bias_30_A_16_112", "Gemm_18_conv_4_off_bias_39_A_16_114" \
  }
#define STAI_NETWORK_WEIGHTS_FORMATS \
  { \
    STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_Q15, STAI_FORMAT_S8, STAI_FORMAT_Q15, STAI_FORMAT_S8, STAI_FORMAT_Q15, STAI_FORMAT_S8, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15 \
  }
#define STAI_NETWORK_WEIGHTS_SIZES \
  { \
    72, 1152, 4608, 6144, 1, 8, 1, 16, 1, 32, 1, 6, 8, 16, 32, 6 \
  }
#define STAI_NETWORK_WEIGHTS_SIZES_BYTES \
  { \
    72, 1152, 4608, 6144, 1, 16, 1, 32, 1, 64, 1, 12, 16, 32, 64, 12 \
  }

#define STAI_NETWORK_WEIGHTS_1_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_1_NAME "Conv2D_4_weights"
#define STAI_NETWORK_WEIGHTS_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_1_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_1_SIZE (72)
#define STAI_NETWORK_WEIGHTS_1_SIZE_BYTES (72)
#define STAI_NETWORK_WEIGHTS_1_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_1_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_1_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_1_BATCH (1)
#define STAI_NETWORK_WEIGHTS_1_RANK (4)
#define STAI_NETWORK_WEIGHTS_1_SHAPE \
  { \
    8, 3, 3, 1 \
  }
#define STAI_NETWORK_WEIGHTS_1_SCALE_OFFSET_NUM (8)
#define STAI_NETWORK_WEIGHTS_1_SCALES \
  { \
    0.000996682560071349, 0.00115034892223775, 0.00108031707350165, 0.00121056253556162, 0.0017524256836623, 0.00129303964786232, 0.00162285030819476, 0.00136452598962933 \
  }
#define STAI_NETWORK_WEIGHTS_1_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_2_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_2_NAME "Conv2D_8_weights"
#define STAI_NETWORK_WEIGHTS_2_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_2_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_2_SIZE (1152)
#define STAI_NETWORK_WEIGHTS_2_SIZE_BYTES (1152)
#define STAI_NETWORK_WEIGHTS_2_CHANNEL (8)
#define STAI_NETWORK_WEIGHTS_2_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_2_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_2_BATCH (8)
#define STAI_NETWORK_WEIGHTS_2_RANK (4)
#define STAI_NETWORK_WEIGHTS_2_SHAPE \
  { \
    16, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_2_SCALE_OFFSET_NUM (16)
#define STAI_NETWORK_WEIGHTS_2_SCALES \
  { \
    0.00216099410317838, 0.00189939863048494, 0.00241913320496678, 0.00195179064758122, 0.00189018039964139, 0.00187939091119915, 0.00203231512568891, 0.00171542132738978, 0.00303659262135625, 0.00166595925111324, 0.00206282828003168, 0.00226150499656796, 0.0023311257828027, 0.00217967131175101, 0.00224502757191658, 0.00216335570439696 \
  }
#define STAI_NETWORK_WEIGHTS_2_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_3_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_3_NAME "Conv2D_13_weights"
#define STAI_NETWORK_WEIGHTS_3_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_3_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_3_SIZE (4608)
#define STAI_NETWORK_WEIGHTS_3_SIZE_BYTES (4608)
#define STAI_NETWORK_WEIGHTS_3_CHANNEL (16)
#define STAI_NETWORK_WEIGHTS_3_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_3_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_3_BATCH (8)
#define STAI_NETWORK_WEIGHTS_3_RANK (5)
#define STAI_NETWORK_WEIGHTS_3_SHAPE \
  { \
    32, 2, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_3_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_3_SCALES \
  { \
    0.00243523670360446, 0.00200935150496662, 0.00325870653614402, 0.00270809535868466, 0.00220558908767998, 0.00265364721417427, 0.0019524444360286, 0.00238358182832599, 0.00250851758755744, 0.00217378605157137, 0.00242043635807931, 0.00205746735446155, 0.00223420979455113, 0.00281731551513076, 0.00207233149558306, 0.00219345814548433, 0.0020200137514621, 0.00219730800017715, 0.00175384571775794, 0.00201154919341207, 0.00234748236835003, 0.00230142218060791, 0.00285451742820442, 0.00204622722230852, 0.0023072762414813, 0.00252864602953196, 0.00223623076453805, 0.00202042632736266, 0.00217237509787083, 0.00235631223767996, 0.0019399767043069, 0.00182722345925868 \
  }
#define STAI_NETWORK_WEIGHTS_3_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_4_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_4_NAME "Gemm_18_weights_transposed_3"
#define STAI_NETWORK_WEIGHTS_4_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_4_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_4_SIZE (6144)
#define STAI_NETWORK_WEIGHTS_4_SIZE_BYTES (6144)
#define STAI_NETWORK_WEIGHTS_4_CHANNEL (1024)
#define STAI_NETWORK_WEIGHTS_4_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_4_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_4_BATCH (128)
#define STAI_NETWORK_WEIGHTS_4_RANK (5)
#define STAI_NETWORK_WEIGHTS_4_SHAPE \
  { \
    6, 8, 1, 1, 128 \
  }
#define STAI_NETWORK_WEIGHTS_4_SCALE_OFFSET_NUM (6)
#define STAI_NETWORK_WEIGHTS_4_SCALES \
  { \
    0.00126883422490209, 0.00143219903111458, 0.00135089410468936, 0.00148734811227769, 0.00133044982794672, 0.00129210168961436 \
  }
#define STAI_NETWORK_WEIGHTS_4_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_5_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_5_NAME "Conv2D_4_zero_off_8"
#define STAI_NETWORK_WEIGHTS_5_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_5_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_5_SIZE (1)
#define STAI_NETWORK_WEIGHTS_5_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_5_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_5_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_5_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_5_RANK (1)
#define STAI_NETWORK_WEIGHTS_5_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_5_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_WEIGHTS_5_SCALES \
  { \
    0.00392156885936856 \
  }
#define STAI_NETWORK_WEIGHTS_5_OFFSETS \
  { \
    0 \
  }

#define STAI_NETWORK_WEIGHTS_6_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_6_NAME "Conv2D_4_off_bias_14"
#define STAI_NETWORK_WEIGHTS_6_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_6_FORMAT (STAI_FORMAT_Q15)
#define STAI_NETWORK_WEIGHTS_6_SIZE (8)
#define STAI_NETWORK_WEIGHTS_6_SIZE_BYTES (16)
#define STAI_NETWORK_WEIGHTS_6_CHANNEL (8)
#define STAI_NETWORK_WEIGHTS_6_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_6_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_6_BATCH (8)
#define STAI_NETWORK_WEIGHTS_6_RANK (3)
#define STAI_NETWORK_WEIGHTS_6_SHAPE \
  { \
    1, 1, 8 \
  }
#define STAI_NETWORK_WEIGHTS_6_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_6_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_6_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_7_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_7_NAME "Conv2D_8_zero_off_17"
#define STAI_NETWORK_WEIGHTS_7_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_7_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_7_SIZE (1)
#define STAI_NETWORK_WEIGHTS_7_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_7_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_7_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_7_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_7_RANK (1)
#define STAI_NETWORK_WEIGHTS_7_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_7_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_WEIGHTS_7_SCALES \
  { \
    0.00159284484107047 \
  }
#define STAI_NETWORK_WEIGHTS_7_OFFSETS \
  { \
    0 \
  }

#define STAI_NETWORK_WEIGHTS_8_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_8_NAME "Conv2D_8_off_bias_23"
#define STAI_NETWORK_WEIGHTS_8_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_8_FORMAT (STAI_FORMAT_Q15)
#define STAI_NETWORK_WEIGHTS_8_SIZE (16)
#define STAI_NETWORK_WEIGHTS_8_SIZE_BYTES (32)
#define STAI_NETWORK_WEIGHTS_8_CHANNEL (16)
#define STAI_NETWORK_WEIGHTS_8_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_8_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_8_BATCH (8)
#define STAI_NETWORK_WEIGHTS_8_RANK (4)
#define STAI_NETWORK_WEIGHTS_8_SHAPE \
  { \
    2, 1, 1, 8 \
  }
#define STAI_NETWORK_WEIGHTS_8_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_8_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_8_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_9_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_9_NAME "Conv2D_13_zero_off_26"
#define STAI_NETWORK_WEIGHTS_9_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_9_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_9_SIZE (1)
#define STAI_NETWORK_WEIGHTS_9_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_9_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_9_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_9_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_9_RANK (1)
#define STAI_NETWORK_WEIGHTS_9_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_9_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_WEIGHTS_9_SCALES \
  { \
    0.00154914485756308 \
  }
#define STAI_NETWORK_WEIGHTS_9_OFFSETS \
  { \
    0 \
  }

#define STAI_NETWORK_WEIGHTS_10_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_10_NAME "Conv2D_13_off_bias_32"
#define STAI_NETWORK_WEIGHTS_10_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_10_FORMAT (STAI_FORMAT_Q15)
#define STAI_NETWORK_WEIGHTS_10_SIZE (32)
#define STAI_NETWORK_WEIGHTS_10_SIZE_BYTES (64)
#define STAI_NETWORK_WEIGHTS_10_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_10_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_10_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_10_BATCH (8)
#define STAI_NETWORK_WEIGHTS_10_RANK (4)
#define STAI_NETWORK_WEIGHTS_10_SHAPE \
  { \
    4, 1, 1, 8 \
  }
#define STAI_NETWORK_WEIGHTS_10_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_10_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_10_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_11_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_11_NAME "Gemm_18_conv_4_zero_off_35"
#define STAI_NETWORK_WEIGHTS_11_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_11_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_11_SIZE (1)
#define STAI_NETWORK_WEIGHTS_11_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_11_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_11_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_11_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_11_RANK (1)
#define STAI_NETWORK_WEIGHTS_11_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_11_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_WEIGHTS_11_SCALES \
  { \
    0.000952695205342025 \
  }
#define STAI_NETWORK_WEIGHTS_11_OFFSETS \
  { \
    0 \
  }

#define STAI_NETWORK_WEIGHTS_12_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_12_NAME "Gemm_18_conv_4_off_bias_41"
#define STAI_NETWORK_WEIGHTS_12_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_12_FORMAT (STAI_FORMAT_Q15)
#define STAI_NETWORK_WEIGHTS_12_SIZE (6)
#define STAI_NETWORK_WEIGHTS_12_SIZE_BYTES (12)
#define STAI_NETWORK_WEIGHTS_12_CHANNEL (6)
#define STAI_NETWORK_WEIGHTS_12_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_12_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_12_BATCH (6)
#define STAI_NETWORK_WEIGHTS_12_RANK (3)
#define STAI_NETWORK_WEIGHTS_12_SHAPE \
  { \
    1, 1, 6 \
  }
#define STAI_NETWORK_WEIGHTS_12_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_12_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_12_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_13_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_13_NAME "Conv2D_4_off_bias_12_A_16_108"
#define STAI_NETWORK_WEIGHTS_13_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_13_FORMAT (STAI_FORMAT_Q15)
#define STAI_NETWORK_WEIGHTS_13_SIZE (8)
#define STAI_NETWORK_WEIGHTS_13_SIZE_BYTES (16)
#define STAI_NETWORK_WEIGHTS_13_CHANNEL (8)
#define STAI_NETWORK_WEIGHTS_13_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_13_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_13_BATCH (8)
#define STAI_NETWORK_WEIGHTS_13_RANK (3)
#define STAI_NETWORK_WEIGHTS_13_SHAPE \
  { \
    1, 1, 8 \
  }
#define STAI_NETWORK_WEIGHTS_13_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_13_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_13_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_14_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_14_NAME "Conv2D_8_off_bias_21_A_16_110"
#define STAI_NETWORK_WEIGHTS_14_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_14_FORMAT (STAI_FORMAT_Q15)
#define STAI_NETWORK_WEIGHTS_14_SIZE (16)
#define STAI_NETWORK_WEIGHTS_14_SIZE_BYTES (32)
#define STAI_NETWORK_WEIGHTS_14_CHANNEL (16)
#define STAI_NETWORK_WEIGHTS_14_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_14_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_14_BATCH (16)
#define STAI_NETWORK_WEIGHTS_14_RANK (3)
#define STAI_NETWORK_WEIGHTS_14_SHAPE \
  { \
    1, 1, 16 \
  }
#define STAI_NETWORK_WEIGHTS_14_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_14_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_14_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_15_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_15_NAME "Conv2D_13_off_bias_30_A_16_112"
#define STAI_NETWORK_WEIGHTS_15_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_15_FORMAT (STAI_FORMAT_Q15)
#define STAI_NETWORK_WEIGHTS_15_SIZE (32)
#define STAI_NETWORK_WEIGHTS_15_SIZE_BYTES (64)
#define STAI_NETWORK_WEIGHTS_15_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_15_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_15_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_15_BATCH (32)
#define STAI_NETWORK_WEIGHTS_15_RANK (3)
#define STAI_NETWORK_WEIGHTS_15_SHAPE \
  { \
    1, 1, 32 \
  }
#define STAI_NETWORK_WEIGHTS_15_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_15_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_15_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_16_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_16_NAME "Gemm_18_conv_4_off_bias_39_A_16_114"
#define STAI_NETWORK_WEIGHTS_16_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_16_FORMAT (STAI_FORMAT_Q15)
#define STAI_NETWORK_WEIGHTS_16_SIZE (6)
#define STAI_NETWORK_WEIGHTS_16_SIZE_BYTES (12)
#define STAI_NETWORK_WEIGHTS_16_CHANNEL (6)
#define STAI_NETWORK_WEIGHTS_16_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_16_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_16_BATCH (6)
#define STAI_NETWORK_WEIGHTS_16_RANK (3)
#define STAI_NETWORK_WEIGHTS_16_SHAPE \
  { \
    1, 1, 6 \
  }
#define STAI_NETWORK_WEIGHTS_16_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_16_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_16_OFFSETS \
  { \
  }
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_NETWORK_WEIGHTS_NUM (0)
#define STAI_NETWORK_WEIGHTS_ALIGNMENTS \
  { \
  }
#define STAI_NETWORK_WEIGHTS_NAMES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_FORMATS \
  { \
  }
#define STAI_NETWORK_WEIGHTS_SIZES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_SIZES_BYTES \
  { \
  }
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0

/******************************** ACTIVATIONS ********************************/
#define STAI_NETWORK_ACTIVATIONS_NUM (0)
#define STAI_NETWORK_ACTIVATIONS_ALIGNMENTS \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_NAMES \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_FORMATS \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_SIZES \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_SIZES_BYTES \
  { \
  }

/****************************** NETWORK MACROS *******************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_NETWORK_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS)
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_NETWORK_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS|STAI_FLAG_WEIGHTS)
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0

#define STAI_NETWORK_ORIGIN_MODEL_NAME "toy_sound_classifier_int8_OE_3_3_1"
#define STAI_NETWORK_C_MODEL_NAME "network"

/*************************** RELATIVE MEMORY POOLS ***************************/
/* no memory pools with relative addresses */

#ifdef __cplusplus
}
#endif

#endif // __STAI_ATON_NETWORK_H
