/*
 * PCMD3180 register driver.
 *
 * This layer is MCU-agnostic. Provide I2C, delay and optional shutdown GPIO
 * callbacks through PCMD3180_BusTypeDef, or use pcmd3180_hal.c on STM32 HAL.
 *
 * NECCS V2 array notes:
 * - Design source: H7_Original/firmware/NECCS/docs/array_32ch_design.html
 *   and array_32ch_coords.csv.
 * - The new hardware plan is 4 x PCMD3180, split across two synchronous TDM
 *   buses: U1/U2 on Bus A and U3/U4 on Bus B.
 * - 32ch at 48 kHz is the default real-time imaging mode.
 * - 16ch at 192 kHz is the high-quality core-array mode. It uses only four
 *   active PDM inputs on each PCMD3180 so the per-bus TDM bandwidth remains
 *   practical.
 *
 * The sample rate is not generated by this driver in the default slave-clock
 * setup. The host SAI or an external clock source must provide matching
 * BCLK/FSYNC. The mode helpers below only keep the PCMD3180 slot map, channel
 * enable masks and expected clock metadata in one place.
 *
 * Typical V2 bring-up flow:
 * 1. Initialize the STM32 I2C and the shared MIC_SHDNZ GPIO.
 * 2. Use PCMD3180_HAL_BusInit() to bind this portable driver to HAL I2C.
 * 3. Initialize one handle and call PCMD3180_HardwareReset() once, because the
 *    four PCMD3180 devices normally share the same shutdown line.
 * 4. Call PCMD3180_ConfigureArrayMode(handles, NULL, &bus,
 *    PCMD3180_ARRAY_MODE_32CH_48K) for the default V2 imaging mode.
 * 5. Configure the host SAI independently from mode_config.expected_bclk_hz.
 *
 * Example:
 *   PCMD3180_ArrayModeConfigTypeDef mode;
 *   PCMD3180_GetArrayModeConfig(PCMD3180_ARRAY_MODE_32CH_48K, &mode);
 *   // mode.expected_bclk_hz is 12.288 MHz per TDM bus for 48 kHz, 16-bit,
 *   // 16-slot capture.
 */

#ifndef PCMD3180_H
#define PCMD3180_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>

#define PCMD3180_I2C_ADDR_0              0x4CU
#define PCMD3180_I2C_ADDR_1              0x4DU
#define PCMD3180_I2C_ADDR_2              0x4EU
#define PCMD3180_I2C_ADDR_3              0x4FU

#define PCMD3180_CHANNEL_1               0x80U
#define PCMD3180_CHANNEL_2               0x40U
#define PCMD3180_CHANNEL_3               0x20U
#define PCMD3180_CHANNEL_4               0x10U
#define PCMD3180_CHANNEL_5               0x08U
#define PCMD3180_CHANNEL_6               0x04U
#define PCMD3180_CHANNEL_7               0x02U
#define PCMD3180_CHANNEL_8               0x01U
#define PCMD3180_CHANNEL_ALL             0xFFU

#define PCMD3180_ARRAY_DEVICE_COUNT      4U
#define PCMD3180_ARRAY_MAX_MICS_PER_DEV  8U

#define PCMD3180_REG_PAGE_CFG            0x00U
#define PCMD3180_REG_SW_RESET            0x01U
#define PCMD3180_REG_SLEEP_CFG           0x02U
#define PCMD3180_REG_SHDN_CFG            0x05U
#define PCMD3180_REG_ASI_CFG0            0x07U
#define PCMD3180_REG_ASI_CFG1            0x08U
#define PCMD3180_REG_ASI_CFG2            0x09U
#define PCMD3180_REG_ASI_CH1             0x0BU
#define PCMD3180_REG_MST_CFG0            0x13U
#define PCMD3180_REG_MST_CFG1            0x14U
#define PCMD3180_REG_ASI_STS             0x15U
#define PCMD3180_REG_CLK_SRC             0x16U
#define PCMD3180_REG_PDMCLK_CFG          0x1FU
#define PCMD3180_REG_PDMIN_CFG           0x20U
#define PCMD3180_REG_GPIO_CFG0           0x21U
#define PCMD3180_REG_GPO_CFG0            0x22U
#define PCMD3180_REG_GPO_CFG1            0x23U
#define PCMD3180_REG_GPO_CFG2            0x24U
#define PCMD3180_REG_GPO_CFG3            0x25U
#define PCMD3180_REG_GPI_CFG0            0x2BU
#define PCMD3180_REG_GPI_CFG1            0x2CU
#define PCMD3180_REG_GPI_MON             0x2FU
#define PCMD3180_REG_CH1_CFG0            0x3CU
#define PCMD3180_REG_CH1_CFG1            0x3DU
#define PCMD3180_REG_DSP_CFG0            0x6BU
#define PCMD3180_REG_DSP_CFG1            0x6CU
#define PCMD3180_REG_IN_CH_EN            0x73U
#define PCMD3180_REG_ASI_OUT_CH_EN       0x74U
#define PCMD3180_REG_PWR_CFG             0x75U
#define PCMD3180_REG_DEV_STS0            0x76U
#define PCMD3180_REG_DEV_STS1            0x77U
#define PCMD3180_REG_INT_LTCH0           0x78U
#define PCMD3180_REG_INT_LTCH1           0x79U

#define PCMD3180_SLEEP_CFG_WAKE          0x81U
#define PCMD3180_SW_RESET_ASSERT         0x01U
#define PCMD3180_PDMCLK_CFG_RESET_MASK   0x40U
#define PCMD3180_GPO_CFG_PDMCLK_OUTPUT   0x41U
#define PCMD3180_GPI_CFG0_DEFAULT        0x45U
#define PCMD3180_GPI_CFG1_DEFAULT        0x67U
#define PCMD3180_PWR_PDM_AND_PLL         0x60U
#define PCMD3180_PWR_MICBIAS             0x80U
#define PCMD3180_CH_CFG0_PDM_INPUT       0x40U

typedef enum
{
    PCMD3180_OK = 0,
    PCMD3180_ERROR = -1,
    PCMD3180_INVALID_ARGUMENT = -2,
    PCMD3180_IO_ERROR = -3,
    PCMD3180_VERIFY_ERROR = -4,
    PCMD3180_TIMEOUT = -5
} PCMD3180_StatusTypeDef;

typedef enum
{
    PCMD3180_SLOT_WIDTH_16_BITS = 0,
    PCMD3180_SLOT_WIDTH_20_BITS = 1,
    PCMD3180_SLOT_WIDTH_24_BITS = 2,
    PCMD3180_SLOT_WIDTH_32_BITS = 3
} PCMD3180_SlotWidthTypeDef;

typedef enum
{
    PCMD3180_PDMCLK_DIV_64FS = 0,
    PCMD3180_PDMCLK_DIV_128FS = 1,
    PCMD3180_PDMCLK_DIV_256FS = 2,
    PCMD3180_PDMCLK_DIV_32FS = 3
} PCMD3180_PdmClockDividerTypeDef;

typedef enum
{
    PCMD3180_HPF_DISABLED = 0,
    PCMD3180_HPF_12HZ_AT_48K = 1,
    PCMD3180_HPF_96HZ_AT_48K = 2,
    PCMD3180_HPF_192HZ_AT_48K = 3
} PCMD3180_HighPassFilterTypeDef;

typedef enum
{
    PCMD3180_SAMPLE_RATE_48K = 48000U,
    PCMD3180_SAMPLE_RATE_96K = 96000U,
    PCMD3180_SAMPLE_RATE_192K = 192000U
} PCMD3180_SampleRateTypeDef;

typedef enum
{
    PCMD3180_TDM_BUS_A = 0,
    PCMD3180_TDM_BUS_B = 1
} PCMD3180_TdmBusTypeDef;

typedef enum
{
    PCMD3180_ARRAY_DEVICE_U1 = 0,
    PCMD3180_ARRAY_DEVICE_U2 = 1,
    PCMD3180_ARRAY_DEVICE_U3 = 2,
    PCMD3180_ARRAY_DEVICE_U4 = 3
} PCMD3180_ArrayDeviceTypeDef;

typedef enum
{
    PCMD3180_ARRAY_MODE_32CH_48K = 0,
    PCMD3180_ARRAY_MODE_CORE16_192K,
    PCMD3180_ARRAY_MODE_HF12_192K,
    PCMD3180_ARRAY_MODE_HOTSPOT8_192K,
    PCMD3180_ARRAY_MODE_MID32_48K,
    PCMD3180_ARRAY_MODE_LOW32_48K,
    PCMD3180_ARRAY_MODE_FAR32_48K
} PCMD3180_ArrayModeTypeDef;

typedef PCMD3180_StatusTypeDef (*PCMD3180_WriteRegFn)(void *context,
                                                      uint8_t address7,
                                                      uint8_t reg,
                                                      uint8_t value);
typedef PCMD3180_StatusTypeDef (*PCMD3180_ReadRegFn)(void *context,
                                                     uint8_t address7,
                                                     uint8_t reg,
                                                     uint8_t *value);
typedef void (*PCMD3180_DelayMsFn)(void *context, uint32_t delay_ms);
typedef void (*PCMD3180_SetShutdownFn)(void *context, uint8_t asserted);

typedef struct
{
    void *context;
    PCMD3180_WriteRegFn write_reg;
    PCMD3180_ReadRegFn read_reg;
    PCMD3180_DelayMsFn delay_ms;
    PCMD3180_SetShutdownFn set_shutdown;
} PCMD3180_BusTypeDef;

typedef struct
{
    uint8_t address7;
    uint8_t current_page;
    uint8_t configured;
    PCMD3180_BusTypeDef bus;
} PCMD3180_HandleTypeDef;

typedef struct
{
    uint8_t start_slot;
    uint8_t input_channel_mask;
    uint8_t output_channel_mask;
    uint8_t logical_channel_count;
    PCMD3180_SlotWidthTypeDef slot_width;
    uint32_t sample_rate_hz;
    uint8_t tdm_slots_per_bus;
    uint32_t expected_bclk_hz;
    uint8_t tdm_tx_offset;
    uint8_t invert_bclk;
    uint8_t invert_fsync;
    PCMD3180_PdmClockDividerTypeDef pdmclk_divider;
    uint8_t pdmin_edge_mask;
    PCMD3180_HighPassFilterTypeDef hpf_select;
    uint8_t enable_micbias;
    uint8_t verify_writes;
} PCMD3180_ConfigTypeDef;

typedef struct
{
    PCMD3180_ArrayDeviceTypeDef device;
    PCMD3180_TdmBusTypeDef tdm_bus;
    uint8_t address7;
    uint8_t start_slot;
    uint8_t input_channel_mask;
    uint8_t output_channel_mask;
    uint8_t mic_count;
    uint8_t mic_id[PCMD3180_ARRAY_MAX_MICS_PER_DEV];
} PCMD3180_ArrayDevicePlanTypeDef;

typedef struct
{
    PCMD3180_ArrayModeTypeDef mode;
    uint32_t sample_rate_hz;
    uint16_t frame_samples;
    PCMD3180_SlotWidthTypeDef slot_width;
    uint8_t tdm_slots_per_bus;
    uint8_t physical_mic_count;
    uint8_t capture_channel_count;
    uint16_t recommended_pair_count;
    uint32_t band_low_hz;
    uint32_t band_high_hz;
    uint32_t expected_bclk_hz;
    PCMD3180_ArrayDevicePlanTypeDef devices[PCMD3180_ARRAY_DEVICE_COUNT];
} PCMD3180_ArrayModeConfigTypeDef;

typedef struct
{
    uint8_t dev_sts0;
    uint8_t dev_sts1;
    uint8_t asi_sts;
    uint8_t int_latch0;
    uint8_t int_latch1;
    uint8_t pwr_cfg;
    uint8_t gpi_mon;
} PCMD3180_StatusSnapshotTypeDef;

PCMD3180_StatusTypeDef PCMD3180_Init(PCMD3180_HandleTypeDef *handle,
                                     const PCMD3180_BusTypeDef *bus,
                                     uint8_t address7);

void PCMD3180_GetDefaultConfig(PCMD3180_ConfigTypeDef *config);

PCMD3180_StatusTypeDef PCMD3180_GetArrayModeConfig(PCMD3180_ArrayModeTypeDef mode,
                                                   PCMD3180_ArrayModeConfigTypeDef *mode_config);

PCMD3180_StatusTypeDef PCMD3180_BuildDeviceConfig(const PCMD3180_ArrayModeConfigTypeDef *mode_config,
                                                  uint32_t device_index,
                                                  PCMD3180_ConfigTypeDef *device_config);

PCMD3180_StatusTypeDef PCMD3180_HardwareReset(PCMD3180_HandleTypeDef *handle,
                                              uint32_t reset_low_ms,
                                              uint32_t settle_ms);

PCMD3180_StatusTypeDef PCMD3180_SoftwareReset(PCMD3180_HandleTypeDef *handle);

PCMD3180_StatusTypeDef PCMD3180_Probe(PCMD3180_HandleTypeDef *handle);

PCMD3180_StatusTypeDef PCMD3180_Configure(PCMD3180_HandleTypeDef *handle,
                                          const PCMD3180_ConfigTypeDef *config);

PCMD3180_StatusTypeDef PCMD3180_ConfigureTdmChain(PCMD3180_HandleTypeDef *handles,
                                                  const uint8_t *addresses,
                                                  uint32_t device_count,
                                                  const PCMD3180_BusTypeDef *bus,
                                                  PCMD3180_ConfigTypeDef config);

PCMD3180_StatusTypeDef PCMD3180_ConfigureArrayMode(PCMD3180_HandleTypeDef *handles,
                                                   const uint8_t *addresses,
                                                   const PCMD3180_BusTypeDef *bus,
                                                   PCMD3180_ArrayModeTypeDef mode);

PCMD3180_StatusTypeDef PCMD3180_SelectPage(PCMD3180_HandleTypeDef *handle,
                                           uint8_t page);

PCMD3180_StatusTypeDef PCMD3180_WriteRegister(PCMD3180_HandleTypeDef *handle,
                                              uint8_t reg,
                                              uint8_t value);

PCMD3180_StatusTypeDef PCMD3180_ReadRegister(PCMD3180_HandleTypeDef *handle,
                                             uint8_t reg,
                                             uint8_t *value);

PCMD3180_StatusTypeDef PCMD3180_ReadStatus(PCMD3180_HandleTypeDef *handle,
                                           PCMD3180_StatusSnapshotTypeDef *status);

uint8_t PCMD3180_CountEnabledChannels(uint8_t channel_mask);

uint8_t PCMD3180_GetSlotWidthBits(PCMD3180_SlotWidthTypeDef slot_width);

uint32_t PCMD3180_CalculateBitClockHz(uint32_t sample_rate_hz,
                                      uint8_t tdm_slots_per_bus,
                                      PCMD3180_SlotWidthTypeDef slot_width);

#ifdef __cplusplus
}
#endif

#endif /* PCMD3180_H */
